{'filters': {'names': {'codetagify': ('pygments.filters', 'CodeTagFilter'),
                       'gobble': ('pygments.filters', 'GobbleFilter'),
                       'highlight': ('pygments.filters', 'NameHighlightFilter'),
                       'keywordcase': ('pygments.filters', 'KeywordCaseFilter'),
                       'raiseonerror': ('pygments.filters',
                                        'RaiseOnErrorTokenFilter'),
                       'symbols': ('pygments.filters', 'SymbolFilter'),
                       'tokenmerge': ('pygments.filters', 'TokenMergeFilter'),
                       'whitespace': ('pygments.filters',
                                      'VisibleWhitespaceFilter')}},
 'formatters': {'exts': {'.bmp': ('pygments.formatters.img',
                                  'BmpImageFormatter'),
                         '.gif': ('pygments.formatters.img',
                                  'GifImageFormatter'),
                         '.htm': ('pygments.formatters.html', 'HtmlFormatter'),
                         '.html': ('pygments.formatters.html', 'HtmlFormatter'),
                         '.jpg': ('pygments.formatters.img',
                                  'JpgImageFormatter'),
                         '.png': ('pygments.formatters.img', 'ImageFormatter'),
                         '.raw': ('pygments.formatters.other',
                                  'RawTokenFormatter'),
                         '.rtf': ('pygments.formatters.rtf', 'RtfFormatter'),
                         '.svg': ('pygments.formatters.svg', 'SvgFormatter'),
                         '.tex': ('pygments.formatters.latex',
                                  'LatexFormatter'),
                         '.txt': ('pygments.formatters.other',
                                  'NullFormatter')},
                'names': {'16m': ('pygments.formatters.terminal256',
                                  'TerminalTrueColorFormatter'),
                          '256': ('pygments.formatters.terminal256',
                                  'Terminal256Formatter'),
                          'BBCode': ('pygments.formatters.bbcode',
                                     'BBCodeFormatter'),
                          'HTML': ('pygments.formatters.html', 'HtmlFormatter'),
                          'IMG': ('pygments.formatters.img', 'ImageFormatter'),
                          'IRC': ('pygments.formatters.irc', 'IRCFormatter'),
                          'LaTeX': ('pygments.formatters.latex',
                                    'LatexFormatter'),
                          'Pango Markup': ('pygments.formatters.pangomarkup',
                                           'PangoMarkupFormatter'),
                          'RTF': ('pygments.formatters.rtf', 'RtfFormatter'),
                          'Raw tokens': ('pygments.formatters.other',
                                         'RawTokenFormatter'),
                          'SVG': ('pygments.formatters.svg', 'SvgFormatter'),
                          'Terminal': ('pygments.formatters.terminal',
                                       'TerminalFormatter'),
                          'Terminal256': ('pygments.formatters.terminal256',
                                          'Terminal256Formatter'),
                          'TerminalTrueColor': ('pygments.formatters.terminal256',
                                                'TerminalTrueColorFormatter'),
                          'Testcase': ('pygments.formatters.other',
                                       'TestcaseFormatter'),
                          'Text only': ('pygments.formatters.other',
                                        'NullFormatter'),
                          'bb': ('pygments.formatters.bbcode',
                                 'BBCodeFormatter'),
                          'bbcode': ('pygments.formatters.bbcode',
                                     'BBCodeFormatter'),
                          'bitmap': ('pygments.formatters.img',
                                     'BmpImageFormatter'),
                          'bmp': ('pygments.formatters.img',
                                  'BmpImageFormatter'),
                          'console': ('pygments.formatters.terminal',
                                      'TerminalFormatter'),
                          'console16m': ('pygments.formatters.terminal256',
                                         'TerminalTrueColorFormatter'),
                          'console256': ('pygments.formatters.terminal256',
                                         'Terminal256Formatter'),
                          'gif': ('pygments.formatters.img',
                                  'GifImageFormatter'),
                          'groff': ('pygments.formatters.groff',
                                    'GroffFormatter'),
                          'html': ('pygments.formatters.html', 'HtmlFormatter'),
                          'img': ('pygments.formatters.img', 'ImageFormatter'),
                          'img_bmp': ('pygments.formatters.img',
                                      'BmpImageFormatter'),
                          'img_gif': ('pygments.formatters.img',
                                      'GifImageFormatter'),
                          'img_jpg': ('pygments.formatters.img',
                                      'JpgImageFormatter'),
                          'irc': ('pygments.formatters.irc', 'IRCFormatter'),
                          'jpeg': ('pygments.formatters.img',
                                   'JpgImageFormatter'),
                          'jpg': ('pygments.formatters.img',
                                  'JpgImageFormatter'),
                          'latex': ('pygments.formatters.latex',
                                    'LatexFormatter'),
                          'null': ('pygments.formatters.other',
                                   'NullFormatter'),
                          'pango': ('pygments.formatters.pangomarkup',
                                    'PangoMarkupFormatter'),
                          'pangomarkup': ('pygments.formatters.pangomarkup',
                                          'PangoMarkupFormatter'),
                          'png': ('pygments.formatters.img', 'ImageFormatter'),
                          'raw': ('pygments.formatters.other',
                                  'RawTokenFormatter'),
                          'roff': ('pygments.formatters.groff',
                                   'GroffFormatter'),
                          'rtf': ('pygments.formatters.rtf', 'RtfFormatter'),
                          'svg': ('pygments.formatters.svg', 'SvgFormatter'),
                          'terminal': ('pygments.formatters.terminal',
                                       'TerminalFormatter'),
                          'terminal16m': ('pygments.formatters.terminal256',
                                          'TerminalTrueColorFormatter'),
                          'terminal256': ('pygments.formatters.terminal256',
                                          'Terminal256Formatter'),
                          'testcase': ('pygments.formatters.other',
                                       'TestcaseFormatter'),
                          'tex': ('pygments.formatters.latex',
                                  'LatexFormatter'),
                          'text': ('pygments.formatters.other',
                                   'NullFormatter'),
                          'tokens': ('pygments.formatters.other',
                                     'RawTokenFormatter'),
                          'troff': ('pygments.formatters.groff',
                                    'GroffFormatter')}},
 'lexers': {'exts': {'.1p': ('pygments.lexers.markup', 'GroffLexer'),
                     '.3pm': ('pygments.lexers.markup', 'GroffLexer'),
                     '.6pl': ('pygments.lexers.perl', 'Perl6Lexer'),
                     '.6pm': ('pygments.lexers.perl', 'Perl6Lexer'),
                     '.ABAP': ('pygments.lexers.business', 'ABAPLexer'),
                     '.ASM': ('pygments.lexers.asm', 'NasmLexer'),
                     '.BAS': ('pygments.lexers.basic', 'QBasicLexer'),
                     '.C': ('pygments.lexers.c_cpp', 'CppLexer'),
                     '.CBL': ('pygments.lexers.business',
                              'CobolFreeformatLexer'),
                     '.COB': ('pygments.lexers.business', 'CobolLexer'),
                     '.CPP': ('pygments.lexers.c_cpp', 'CppLexer'),
                     '.CPY': ('pygments.lexers.business', 'CobolLexer'),
                     '.F': ('pygments.lexers.fortran', 'FortranFixedLexer'),
                     '.F03': ('pygments.lexers.fortran', 'FortranLexer'),
                     '.F90': ('pygments.lexers.fortran', 'FortranLexer'),
                     '.G': ('pygments.lexers.parsers', 'AntlrCppLexer'),
                     '.H': ('pygments.lexers.c_cpp', 'CppLexer'),
                     '.ICON': ('pygments.lexers.unicon', 'IconLexer'),
                     '.MIPS': ('pygments.lexers.mips', 'MIPSLexer'),
                     '.P': ('pygments.lexers.cplint', 'CplintLexer'),
                     '.PRG': ('pygments.lexers.foxpro', 'FoxProLexer'),
                     '.R': ('pygments.lexers.r', 'SLexer'),
                     '.Rd': ('pygments.lexers.r', 'RdLexer'),
                     '.Renviron': ('pygments.lexers.r', 'SLexer'),
                     '.Rhistory': ('pygments.lexers.r', 'SLexer'),
                     '.Rout': ('pygments.lexers.r', 'RConsoleLexer'),
                     '.Rprofile': ('pygments.lexers.r', 'SLexer'),
                     '.S': ('pygments.lexers.asm', 'GasLexer'),
                     '.SAS': ('pygments.lexers.sas', 'SASLexer'),
                     '.SRCINFO': ('pygments.lexers.srcinfo', 'SrcinfoLexer'),
                     '.VBS': ('pygments.lexers.basic', 'VBScriptLexer'),
                     '.[1-9]': ('pygments.lexers.markup', 'GroffLexer'),
                     '.[gs]sed': ('pygments.lexers.textedit', 'SedLexer'),
                     '.abap': ('pygments.lexers.business', 'ABAPLexer'),
                     '.abnf': ('pygments.lexers.grammar_notation', 'AbnfLexer'),
                     '.ada': ('pygments.lexers.ada', 'AdaLexer'),
                     '.adb': ('pygments.lexers.ada', 'AdaLexer'),
                     '.adl': ('pygments.lexers.archetype', 'AdlLexer'),
                     '.adlf': ('pygments.lexers.archetype', 'AdlLexer'),
                     '.adls': ('pygments.lexers.archetype', 'AdlLexer'),
                     '.adlx': ('pygments.lexers.archetype', 'AdlLexer'),
                     '.ado': ('pygments.lexers.stata', 'StataLexer'),
                     '.ads': ('pygments.lexers.ada', 'AdaLexer'),
                     '.aes': ('pygments.lexers.sophia', 'SophiaLexer'),
                     '.agda': ('pygments.lexers.haskell', 'AgdaLexer'),
                     '.aheui': ('pygments.lexers.esoteric', 'AheuiLexer'),
                     '.ahk': ('pygments.lexers.automation', 'AutohotkeyLexer'),
                     '.ahkl': ('pygments.lexers.automation', 'AutohotkeyLexer'),
                     '.aj': ('pygments.lexers.jvm', 'AspectJLexer'),
                     '.alg': ('pygments.lexers.pascal', 'PortugolLexer'),
                     '.als': ('pygments.lexers.dsls', 'AlloyLexer'),
                     '.ans': ('pygments.lexers.apdlexer', 'apdlexer'),
                     '.apl': ('pygments.lexers.apl', 'APLLexer'),
                     '.aplc': ('pygments.lexers.apl', 'APLLexer'),
                     '.aplf': ('pygments.lexers.apl', 'APLLexer'),
                     '.apli': ('pygments.lexers.apl', 'APLLexer'),
                     '.apln': ('pygments.lexers.apl', 'APLLexer'),
                     '.aplo': ('pygments.lexers.apl', 'APLLexer'),
                     '.applescript': ('pygments.lexers.scripting',
                                      'AppleScriptLexer'),
                     '.arexx': ('pygments.lexers.scripting', 'RexxLexer'),
                     '.art': ('pygments.lexers.arturo', 'ArturoLexer'),
                     '.arw': ('pygments.lexers.arrow', 'ArrowLexer'),
                     '.as': ('pygments.lexers.actionscript',
                             'ActionScript3Lexer'),
                     '.asax': ('pygments.lexers.dotnet', 'CSharpAspxLexer'),
                     '.asc': ('pygments.lexers.asc', 'AscLexer'),
                     '.ascx': ('pygments.lexers.dotnet', 'CSharpAspxLexer'),
                     '.ashx': ('pygments.lexers.dotnet', 'CSharpAspxLexer'),
                     '.asm': ('pygments.lexers.asm', 'NasmLexer'),
                     '.asmx': ('pygments.lexers.dotnet', 'CSharpAspxLexer'),
                     '.asn1': ('pygments.lexers.asn1', 'Asn1Lexer'),
                     '.aspx': ('pygments.lexers.dotnet', 'CSharpAspxLexer'),
                     '.asy': ('pygments.lexers.graphics', 'AsymptoteLexer'),
                     '.at': ('pygments.lexers.ambient', 'AmbientTalkLexer'),
                     '.au3': ('pygments.lexers.automation', 'AutoItLexer'),
                     '.aug': ('pygments.lexers.configs', 'AugeasLexer'),
                     '.automount': ('pygments.lexers.configs', 'SystemdLexer'),
                     '.aux': ('pygments.lexers.markup', 'TexLexer'),
                     '.awk': ('pygments.lexers.textedit', 'AwkLexer'),
                     '.axd': ('pygments.lexers.dotnet', 'CSharpAspxLexer'),
                     '.b': ('pygments.lexers.esoteric', 'BrainfuckLexer'),
                     '.bare': ('pygments.lexers.bare', 'BareLexer'),
                     '.bas': ('pygments.lexers.basic', 'QBasicLexer'),
                     '.bash': ('pygments.lexers.shell', 'BashLexer'),
                     '.bashrc': ('pygments.lexers.shell', 'BashLexer'),
                     '.bat': ('pygments.lexers.shell', 'BatchLexer'),
                     '.bb': ('pygments.lexers.basic', 'BlitzBasicLexer'),
                     '.bbc': ('pygments.lexers.basic', 'BBCBasicLexer'),
                     '.bc': ('pygments.lexers.algebra', 'BCLexer'),
                     '.be': ('pygments.lexers.berry', 'BerryLexer'),
                     '.befunge': ('pygments.lexers.esoteric', 'BefungeLexer'),
                     '.bf': ('pygments.lexers.esoteric', 'BrainfuckLexer'),
                     '.bib': ('pygments.lexers.bibtex', 'BibTeXLexer'),
                     '.blp': ('pygments.lexers.blueprint', 'BlueprintLexer'),
                     '.bmx': ('pygments.lexers.basic', 'BlitzMaxLexer'),
                     '.bnf': ('pygments.lexers.grammar_notation', 'BnfLexer'),
                     '.boa': ('pygments.lexers.boa', 'BoaLexer'),
                     '.boo': ('pygments.lexers.dotnet', 'BooLexer'),
                     '.bpl': ('pygments.lexers.verification', 'BoogieLexer'),
                     '.bqn': ('pygments.lexers.bqn', 'BQNLexer'),
                     '.bro': ('pygments.lexers.dsls', 'ZeekLexer'),
                     '.bst': ('pygments.lexers.bibtex', 'BSTLexer'),
                     '.bug': ('pygments.lexers.modeling', 'BugsLexer'),
                     '.bzl': ('pygments.lexers.python', 'PythonLexer'),
                     '.c': ('pygments.lexers.c_cpp', 'CLexer'),
                     '.c++': ('pygments.lexers.c_cpp', 'CppLexer'),
                     '.c++-objdump': ('pygments.lexers.asm', 'CppObjdumpLexer'),
                     '.c-objdump': ('pygments.lexers.asm', 'CObjdumpLexer'),
                     '.cadl': ('pygments.lexers.archetype', 'CadlLexer'),
                     '.camkes': ('pygments.lexers.esoteric', 'CAmkESLexer'),
                     '.capnp': ('pygments.lexers.capnproto', 'CapnProtoLexer'),
                     '.carbon': ('pygments.lexers.carbon', 'CarbonLexer'),
                     '.cbl': ('pygments.lexers.business',
                              'CobolFreeformatLexer'),
                     '.cc': ('pygments.lexers.c_cpp', 'CppLexer'),
                     '.cddl': ('pygments.lexers.cddl', 'CddlLexer'),
                     '.cdf': ('pygments.lexers.algebra', 'MathematicaLexer'),
                     '.cdl': ('pygments.lexers.esoteric', 'CapDLLexer'),
                     '.ceylon': ('pygments.lexers.jvm', 'CeylonLexer'),
                     '.cf': ('pygments.lexers.configs', 'Cfengine3Lexer'),
                     '.cfc': ('pygments.lexers.templates',
                              'ColdfusionCFCLexer'),
                     '.cfg': ('pygments.lexers.configs', 'IniLexer'),
                     '.cfm': ('pygments.lexers.templates',
                              'ColdfusionHtmlLexer'),
                     '.cfml': ('pygments.lexers.templates',
                               'ColdfusionHtmlLexer'),
                     '.chai': ('pygments.lexers.scripting', 'ChaiscriptLexer'),
                     '.chpl': ('pygments.lexers.chapel', 'ChapelLexer'),
                     '.ci': ('pygments.lexers.c_like', 'CharmciLexer'),
                     '.cirru': ('pygments.lexers.webmisc', 'CirruLexer'),
                     '.cjs': ('pygments.lexers.javascript', 'JavascriptLexer'),
                     '.cl': ('pygments.lexers.vip', 'VisualPrologLexer'),
                     '.clay': ('pygments.lexers.c_like', 'ClayLexer'),
                     '.clj': ('pygments.lexers.jvm', 'ClojureLexer'),
                     '.cljc': ('pygments.lexers.jvm', 'ClojureLexer'),
                     '.cljs': ('pygments.lexers.jvm', 'ClojureScriptLexer'),
                     '.cls': ('pygments.lexers.business', 'OpenEdgeLexer'),
                     '.cmake': ('pygments.lexers.make', 'CMakeLexer'),
                     '.cmd': ('pygments.lexers.shell', 'BatchLexer'),
                     '.cml': ('pygments.lexers.comal', 'Comal80Lexer'),
                     '.cob': ('pygments.lexers.business', 'CobolLexer'),
                     '.coffee': ('pygments.lexers.javascript',
                                 'CoffeeScriptLexer'),
                     '.comal': ('pygments.lexers.comal', 'Comal80Lexer'),
                     '.cp': ('pygments.lexers.c_cpp', 'CppLexer'),
                     '.cpl': ('pygments.lexers.cplint', 'CplintLexer'),
                     '.cpp': ('pygments.lexers.c_cpp', 'CppLexer'),
                     '.cpp-objdump': ('pygments.lexers.asm', 'CppObjdumpLexer'),
                     '.cps': ('pygments.lexers.oberon', 'ComponentPascalLexer'),
                     '.cpsa': ('pygments.lexers.lisp', 'CPSALexer'),
                     '.cpy': ('pygments.lexers.business', 'CobolLexer'),
                     '.cr': ('pygments.lexers.crystal', 'CrystalLexer'),
                     '.crmsh': ('pygments.lexers.dsls', 'CrmshLexer'),
                     '.croc': ('pygments.lexers.d', 'CrocLexer'),
                     '.cry': ('pygments.lexers.haskell', 'CryptolLexer'),
                     '.cs': ('pygments.lexers.dotnet', 'CSharpLexer'),
                     '.csd': ('pygments.lexers.csound', 'CsoundDocumentLexer'),
                     '.csh': ('pygments.lexers.shell', 'TcshLexer'),
                     '.csl': ('pygments.lexers.kusto', 'KustoLexer'),
                     '.css': ('pygments.lexers.css', 'CssLexer'),
                     '.css.in': ('pygments.lexers.markup',
                                 'MozPreprocCssLexer'),
                     '.css.j2': ('pygments.lexers.templates', 'CssDjangoLexer'),
                     '.css.jinja2': ('pygments.lexers.templates',
                                     'CssDjangoLexer'),
                     '.cssul4': ('pygments.lexers.ul4', 'CSSUL4Lexer'),
                     '.cu': ('pygments.lexers.c_like', 'CudaLexer'),
                     '.cuh': ('pygments.lexers.c_like', 'CudaLexer'),
                     '.cw': ('pygments.lexers.esoteric', 'RedcodeLexer'),
                     '.cxx': ('pygments.lexers.c_cpp', 'CppLexer'),
                     '.cxx-objdump': ('pygments.lexers.asm', 'CppObjdumpLexer'),
                     '.cyp': ('pygments.lexers.graph', 'CypherLexer'),
                     '.cypher': ('pygments.lexers.graph', 'CypherLexer'),
                     '.d': ('pygments.lexers.d', 'DLexer'),
                     '.d-objdump': ('pygments.lexers.asm', 'DObjdumpLexer'),
                     '.darcspatch': ('pygments.lexers.diff', 'DarcsPatchLexer'),
                     '.dart': ('pygments.lexers.javascript', 'DartLexer'),
                     '.dasm': ('pygments.lexers.asm', 'Dasm16Lexer'),
                     '.dasm16': ('pygments.lexers.asm', 'Dasm16Lexer'),
                     '.dax': ('pygments.lexers.dax', 'DaxLexer'),
                     '.dcl': ('pygments.lexers.clean', 'CleanLexer'),
                     '.decls': ('pygments.lexers.basic', 'BlitzBasicLexer'),
                     '.def': ('pygments.lexers.configs', 'SingularityLexer'),
                     '.desktop': ('pygments.lexers.configs', 'DesktopLexer'),
                     '.device': ('pygments.lexers.configs', 'SystemdLexer'),
                     '.dg': ('pygments.lexers.python', 'DgLexer'),
                     '.di': ('pygments.lexers.d', 'DLexer'),
                     '.diff': ('pygments.lexers.diff', 'DiffLexer'),
                     '.dmesg': ('pygments.lexers.textfmts', 'KernelLogLexer'),
                     '.do': ('pygments.lexers.stata', 'StataLexer'),
                     '.docker': ('pygments.lexers.configs', 'DockerLexer'),
                     '.dot': ('pygments.lexers.graphviz', 'GraphvizLexer'),
                     '.dpatch': ('pygments.lexers.diff', 'DarcsPatchLexer'),
                     '.dpr': ('pygments.lexers.pascal', 'DelphiLexer'),
                     '.dtd': ('pygments.lexers.html', 'DtdLexer'),
                     '.dts': ('pygments.lexers.devicetree', 'DevicetreeLexer'),
                     '.dtsi': ('pygments.lexers.devicetree', 'DevicetreeLexer'),
                     '.duby': ('pygments.lexers.ruby', 'RubyLexer'),
                     '.duel': ('pygments.lexers.webmisc', 'DuelLexer'),
                     '.dyalog': ('pygments.lexers.apl', 'APLLexer'),
                     '.dyl': ('pygments.lexers.dylan', 'DylanLexer'),
                     '.dylan': ('pygments.lexers.dylan', 'DylanLexer'),
                     '.dylan-console': ('pygments.lexers.dylan',
                                        'DylanConsoleLexer'),
                     '.e': ('pygments.lexers.eiffel', 'EiffelLexer'),
                     '.ebnf': ('pygments.lexers.parsers', 'EbnfLexer'),
                     '.ebuild': ('pygments.lexers.shell', 'BashLexer'),
                     '.ec': ('pygments.lexers.c_like', 'ECLexer'),
                     '.ecl': ('pygments.lexers.ecl', 'ECLLexer'),
                     '.eclass': ('pygments.lexers.shell', 'BashLexer'),
                     '.editorconfig': ('pygments.lexers.configs', 'IniLexer'),
                     '.edp': ('pygments.lexers.freefem', 'FreeFemLexer'),
                     '.eex': ('pygments.lexers.erlang', 'ElixirLexer'),
                     '.eg': ('pygments.lexers.javascript', 'EarlGreyLexer'),
                     '.eh': ('pygments.lexers.c_like', 'ECLexer'),
                     '.el': ('pygments.lexers.lisp', 'EmacsLispLexer'),
                     '.elm': ('pygments.lexers.elm', 'ElmLexer'),
                     '.elpi': ('pygments.lexers.elpi', 'ElpiLexer'),
                     '.eml': ('pygments.lexers.email', 'EmailLexer'),
                     '.eps': ('pygments.lexers.graphics', 'PostScriptLexer'),
                     '.erl': ('pygments.lexers.erlang', 'ErlangLexer'),
                     '.erl-sh': ('pygments.lexers.erlang', 'ErlangShellLexer'),
                     '.es': ('pygments.lexers.erlang', 'ErlangLexer'),
                     '.escript': ('pygments.lexers.erlang', 'ErlangLexer'),
                     '.evoque': ('pygments.lexers.templates', 'EvoqueLexer'),
                     '.ex': ('pygments.lexers.erlang', 'ElixirLexer'),
                     '.exec': ('pygments.lexers.shell', 'ExeclineLexer'),
                     '.exheres-0': ('pygments.lexers.shell', 'BashLexer'),
                     '.exlib': ('pygments.lexers.shell', 'BashLexer'),
                     '.explain': ('pygments.lexers.sql',
                                  'PostgresExplainLexer'),
                     '.exrc': ('pygments.lexers.textedit', 'VimLexer'),
                     '.exs': ('pygments.lexers.erlang', 'ElixirLexer'),
                     '.exw': ('pygments.lexers.phix', 'PhixLexer'),
                     '.ezt': ('pygments.lexers.scripting', 'EasytrieveLexer'),
                     '.f': ('pygments.lexers.fortran', 'FortranFixedLexer'),
                     '.f03': ('pygments.lexers.fortran', 'FortranLexer'),
                     '.f90': ('pygments.lexers.fortran', 'FortranLexer'),
                     '.factor': ('pygments.lexers.factor', 'FactorLexer'),
                     '.fan': ('pygments.lexers.fantom', 'FantomLexer'),
                     '.fancypack': ('pygments.lexers.ruby', 'FancyLexer'),
                     '.fc': ('pygments.lexers.func', 'FuncLexer'),
                     '.feature': ('pygments.lexers.testing', 'GherkinLexer'),
                     '.fhtml': ('pygments.lexers.templates', 'VelocityLexer'),
                     '.fif': ('pygments.lexers.fift', 'FiftLexer'),
                     '.fish': ('pygments.lexers.shell', 'FishShellLexer'),
                     '.flo': ('pygments.lexers.floscript', 'FloScriptLexer'),
                     '.flx': ('pygments.lexers.felix', 'FelixLexer'),
                     '.flxh': ('pygments.lexers.felix', 'FelixLexer'),
                     '.fnl': ('pygments.lexers.lisp', 'FennelLexer'),
                     '.frag': ('pygments.lexers.graphics', 'GLShaderLexer'),
                     '.frt': ('pygments.lexers.forth', 'ForthLexer'),
                     '.fs': ('pygments.lexers.forth', 'ForthLexer'),
                     '.fsi': ('pygments.lexers.dotnet', 'FSharpLexer'),
                     '.fst': ('pygments.lexers.ml', 'FStarLexer'),
                     '.fsti': ('pygments.lexers.ml', 'FStarLexer'),
                     '.fsx': ('pygments.lexers.dotnet', 'FSharpLexer'),
                     '.fun': ('pygments.lexers.ml', 'SMLLexer'),
                     '.func': ('pygments.lexers.func', 'FuncLexer'),
                     '.fut': ('pygments.lexers.futhark', 'FutharkLexer'),
                     '.fy': ('pygments.lexers.ruby', 'FancyLexer'),
                     '.g': ('pygments.lexers.parsers', 'AntlrCppLexer'),
                     '.gap': ('pygments.lexers.algebra', 'GAPLexer'),
                     '.gcode': ('pygments.lexers.gcodelexer', 'GcodeLexer'),
                     '.gd': ('pygments.lexers.gdscript', 'GDScriptLexer'),
                     '.gdc': ('pygments.lexers.business', 'GoodDataCLLexer'),
                     '.gemspec': ('pygments.lexers.ruby', 'RubyLexer'),
                     '.geo': ('pygments.lexers.graphics', 'GLShaderLexer'),
                     '.gi': ('pygments.lexers.algebra', 'GAPLexer'),
                     '.gleam': ('pygments.lexers.gleam', 'GleamLexer'),
                     '.go': ('pygments.lexers.go', 'GoLexer'),
                     '.golo': ('pygments.lexers.jvm', 'GoloLexer'),
                     '.googlesql': ('pygments.lexers.sql', 'GoogleSqlLexer'),
                     '.googlesql.sql': ('pygments.lexers.sql',
                                        'GoogleSqlLexer'),
                     '.gradle': ('pygments.lexers.jvm', 'GroovyLexer'),
                     '.graph': ('pygments.lexers.roboconf',
                                'RoboconfGraphLexer'),
                     '.graphql': ('pygments.lexers.graphql', 'GraphQLLexer'),
                     '.groovy': ('pygments.lexers.jvm', 'GroovyLexer'),
                     '.gs': ('pygments.lexers.jvm', 'GosuLexer'),
                     '.gsp': ('pygments.lexers.jvm', 'GosuLexer'),
                     '.gsql': ('pygments.lexers.gsql', 'GSQLLexer'),
                     '.gst': ('pygments.lexers.jvm', 'GosuTemplateLexer'),
                     '.gsx': ('pygments.lexers.jvm', 'GosuLexer'),
                     '.gv': ('pygments.lexers.graphviz', 'GraphvizLexer'),
                     '.gvimrc': ('pygments.lexers.textedit', 'VimLexer'),
                     '.h': ('pygments.lexers.c_cpp', 'CLexer'),
                     '.h++': ('pygments.lexers.c_cpp', 'CppLexer'),
                     '.ha': ('pygments.lexers.hare', 'HareLexer'),
                     '.haml': ('pygments.lexers.html', 'HamlLexer'),
                     '.handlebars': ('pygments.lexers.templates',
                                     'HandlebarsHtmlLexer'),
                     '.hbs': ('pygments.lexers.templates',
                              'HandlebarsHtmlLexer'),
                     '.hcl': ('pygments.lexers.configs', 'TerraformLexer'),
                     '.hdp': ('pygments.lexers.dylan', 'DylanLidLexer'),
                     '.hh': ('pygments.lexers.c_cpp', 'CppLexer'),
                     '.hlsl': ('pygments.lexers.graphics', 'HLSLShaderLexer'),
                     '.hlsli': ('pygments.lexers.graphics', 'HLSLShaderLexer'),
                     '.hpp': ('pygments.lexers.c_cpp', 'CppLexer'),
                     '.hrl': ('pygments.lexers.erlang', 'ErlangLexer'),
                     '.hs': ('pygments.lexers.haskell', 'HaskellLexer'),
                     '.hsail': ('pygments.lexers.asm', 'HsailLexer'),
                     '.htaccess': ('pygments.lexers.configs',
                                   'ApacheConfLexer'),
                     '.htm': ('pygments.lexers.html', 'HtmlLexer'),
                     '.htm.j2': ('pygments.lexers.templates',
                                 'HtmlDjangoLexer'),
                     '.htm.jinja2': ('pygments.lexers.templates',
                                     'HtmlDjangoLexer'),
                     '.html': ('pygments.lexers.html', 'HtmlLexer'),
                     '.html.j2': ('pygments.lexers.templates',
                                  'HtmlDjangoLexer'),
                     '.html.jinja2': ('pygments.lexers.templates',
                                      'HtmlDjangoLexer'),
                     '.htmlul4': ('pygments.lexers.ul4', 'HTMLUL4Lexer'),
                     '.hx': ('pygments.lexers.haxe', 'HaxeLexer'),
                     '.hxml': ('pygments.lexers.haxe', 'HxmlLexer'),
                     '.hxsl': ('pygments.lexers.haxe', 'HaxeLexer'),
                     '.hxx': ('pygments.lexers.c_cpp', 'CppLexer'),
                     '.hy': ('pygments.lexers.lisp', 'HyLexer'),
                     '.hyb': ('pygments.lexers.scripting', 'HybrisLexer'),
                     '.i': ('pygments.lexers.vip', 'VisualPrologLexer'),
                     '.i6t': ('pygments.lexers.int_fiction',
                              'Inform6TemplateLexer'),
                     '.i7x': ('pygments.lexers.int_fiction', 'Inform7Lexer'),
                     '.icl': ('pygments.lexers.clean', 'CleanLexer'),
                     '.icn': ('pygments.lexers.unicon', 'UniconLexer'),
                     '.icon': ('pygments.lexers.unicon', 'IconLexer'),
                     '.idc': ('pygments.lexers.c_cpp', 'CLexer'),
                     '.idl': ('pygments.lexers.c_like', 'OmgIdlLexer'),
                     '.idl4': ('pygments.lexers.esoteric', 'CAmkESLexer'),
                     '.idr': ('pygments.lexers.haskell', 'IdrisLexer'),
                     '.ijs': ('pygments.lexers.j', 'JLexer'),
                     '.ik': ('pygments.lexers.jvm', 'IokeLexer'),
                     '.inc': ('pygments.lexers.php', 'PhpLexer'),
                     '.inf': ('pygments.lexers.configs', 'IniLexer'),
                     '.ini': ('pygments.lexers.configs', 'IniLexer'),
                     '.ino': ('pygments.lexers.c_like', 'ArduinoLexer'),
                     '.instances': ('pygments.lexers.roboconf',
                                    'RoboconfInstancesLexer'),
                     '.intr': ('pygments.lexers.dylan', 'DylanLexer'),
                     '.io': ('pygments.lexers.iolang', 'IoLexer'),
                     '.ipf': ('pygments.lexers.igor', 'IgorLexer'),
                     '.isa': ('pygments.lexers.amdgpu', 'AMDGPULexer'),
                     '.j': ('pygments.lexers.jvm', 'JasminLexer'),
                     '.jade': ('pygments.lexers.html', 'PugLexer'),
                     '.jag': ('pygments.lexers.modeling', 'JagsLexer'),
                     '.janet': ('pygments.lexers.lisp', 'JanetLexer'),
                     '.java': ('pygments.lexers.jvm', 'JavaLexer'),
                     '.jbst': ('pygments.lexers.webmisc', 'DuelLexer'),
                     '.jcl': ('pygments.lexers.scripting', 'JclLexer'),
                     '.jdn': ('pygments.lexers.lisp', 'JanetLexer'),
                     '.jl': ('pygments.lexers.julia', 'JuliaLexer'),
                     '.jp': ('pygments.lexers.jmespath', 'JMESPathLexer'),
                     '.js': ('pygments.lexers.javascript', 'JavascriptLexer'),
                     '.js.in': ('pygments.lexers.markup',
                                'MozPreprocJavascriptLexer'),
                     '.js.j2': ('pygments.lexers.templates',
                                'JavascriptDjangoLexer'),
                     '.js.jinja2': ('pygments.lexers.templates',
                                    'JavascriptDjangoLexer'),
                     '.jsgf': ('pygments.lexers.grammar_notation', 'JsgfLexer'),
                     '.jslt': ('pygments.lexers.jslt', 'JSLTLexer'),
                     '.jsm': ('pygments.lexers.javascript', 'JavascriptLexer'),
                     '.json': ('pygments.lexers.data', 'JsonLexer'),
                     '.json5': ('pygments.lexers.json5', 'Json5Lexer'),
                     '.jsonl': ('pygments.lexers.data', 'JsonLexer'),
                     '.jsonld': ('pygments.lexers.data', 'JsonLdLexer'),
                     '.jsonnet': ('pygments.lexers.jsonnet', 'JsonnetLexer'),
                     '.jsp': ('pygments.lexers.templates', 'JspLexer'),
                     '.jsul4': ('pygments.lexers.ul4', 'JavascriptUL4Lexer'),
                     '.jsx': ('pygments.lexers.jsx', 'JsxLexer'),
                     '.juttle': ('pygments.lexers.javascript', 'JuttleLexer'),
                     '.jy': ('pygments.lexers.python', 'PythonLexer'),
                     '.k': ('pygments.lexers.q', 'KLexer'),
                     '.kal': ('pygments.lexers.javascript', 'KalLexer'),
                     '.kid': ('pygments.lexers.templates', 'GenshiLexer'),
                     '.kif': ('pygments.lexers.lisp', 'NewLispLexer'),
                     '.kk': ('pygments.lexers.haskell', 'KokaLexer'),
                     '.kki': ('pygments.lexers.haskell', 'KokaLexer'),
                     '.kmsg': ('pygments.lexers.textfmts', 'KernelLogLexer'),
                     '.kn': ('pygments.lexers.kuin', 'KuinLexer'),
                     '.kql': ('pygments.lexers.kusto', 'KustoLexer'),
                     '.ksh': ('pygments.lexers.shell', 'BashLexer'),
                     '.kshrc': ('pygments.lexers.shell', 'BashLexer'),
                     '.kt': ('pygments.lexers.jvm', 'KotlinLexer'),
                     '.kts': ('pygments.lexers.jvm', 'KotlinLexer'),
                     '.kusto': ('pygments.lexers.kusto', 'KustoLexer'),
                     '.lagda': ('pygments.lexers.haskell', 'LiterateAgdaLexer'),
                     '.lasso': ('pygments.lexers.javascript', 'LassoLexer'),
                     '.lasso[89]': ('pygments.lexers.javascript', 'LassoLexer'),
                     '.lcry': ('pygments.lexers.haskell',
                               'LiterateCryptolLexer'),
                     '.ldaprc': ('pygments.lexers.ldap', 'LdaprcLexer'),
                     '.ldif': ('pygments.lexers.ldap', 'LdifLexer'),
                     '.lean': ('pygments.lexers.lean', 'Lean4Lexer'),
                     '.leex': ('pygments.lexers.erlang', 'ElixirLexer'),
                     '.less': ('pygments.lexers.css', 'LessCssLexer'),
                     '.lgt': ('pygments.lexers.prolog', 'LogtalkLexer'),
                     '.lhs': ('pygments.lexers.haskell',
                              'LiterateHaskellLexer'),
                     '.libsonnet': ('pygments.lexers.jsonnet', 'JsonnetLexer'),
                     '.lid': ('pygments.lexers.dylan', 'DylanLidLexer'),
                     '.lidr': ('pygments.lexers.haskell', 'LiterateIdrisLexer'),
                     '.liquid': ('pygments.lexers.templates', 'LiquidLexer'),
                     '.lisp': ('pygments.lexers.lisp', 'CommonLispLexer'),
                     '.ll': ('pygments.lexers.asm', 'LlvmLexer'),
                     '.load': ('pygments.lexers.shell', 'FishShellLexer'),
                     '.logtalk': ('pygments.lexers.prolog', 'LogtalkLexer'),
                     '.lpad': ('pygments.lexers.cplint', 'CplintLexer'),
                     '.ls': ('pygments.lexers.javascript', 'LiveScriptLexer'),
                     '.lsl': ('pygments.lexers.scripting', 'LSLLexer'),
                     '.lsp': ('pygments.lexers.lisp', 'NewLispLexer'),
                     '.lua': ('pygments.lexers.scripting', 'LuaLexer'),
                     '.luau': ('pygments.lexers.scripting', 'LuauLexer'),
                     '.ly': ('pygments.lexers.lilypond', 'LilyPondLexer'),
                     '.m': ('pygments.lexers.matlab', 'MatlabLexer'),
                     '.m2': ('pygments.lexers.macaulay2', 'Macaulay2Lexer'),
                     '.ma': ('pygments.lexers.algebra', 'MathematicaLexer'),
                     '.mac': ('pygments.lexers.maxima', 'MaximaLexer'),
                     '.mak': ('pygments.lexers.make', 'MakefileLexer'),
                     '.man': ('pygments.lexers.markup', 'GroffLexer'),
                     '.mao': ('pygments.lexers.templates', 'MakoLexer'),
                     '.maql': ('pygments.lexers.business', 'MaqlLexer'),
                     '.markdown': ('pygments.lexers.markup', 'MarkdownLexer'),
                     '.mask': ('pygments.lexers.javascript', 'MaskLexer'),
                     '.max': ('pygments.lexers.maxima', 'MaximaLexer'),
                     '.mc': ('pygments.lexers.templates', 'MasonLexer'),
                     '.mcfunction': ('pygments.lexers.minecraft',
                                     'MCFunctionLexer'),
                     '.mcschema': ('pygments.lexers.minecraft',
                                   'MCSchemaLexer'),
                     '.md': ('pygments.lexers.markup', 'MarkdownLexer'),
                     '.mhtml': ('pygments.lexers.templates', 'MasonLexer'),
                     '.mi': ('pygments.lexers.templates', 'MasonLexer'),
                     '.mips': ('pygments.lexers.mips', 'MIPSLexer'),
                     '.mir': ('pygments.lexers.asm', 'LlvmMirLexer'),
                     '.mjs': ('pygments.lexers.javascript', 'JavascriptLexer'),
                     '.mk': ('pygments.lexers.make', 'MakefileLexer'),
                     '.ml': ('pygments.lexers.ml', 'OcamlLexer'),
                     '.mli': ('pygments.lexers.ml', 'OcamlLexer'),
                     '.mll': ('pygments.lexers.ml', 'OcamlLexer'),
                     '.mly': ('pygments.lexers.ml', 'OcamlLexer'),
                     '.mm': ('pygments.lexers.objective', 'ObjectiveCppLexer'),
                     '.mo': ('pygments.lexers.modeling', 'ModelicaLexer'),
                     '.mod': ('pygments.lexers.modula2', 'Modula2Lexer'),
                     '.mojo': ('pygments.lexers.mojo', 'MojoLexer'),
                     '.monkey': ('pygments.lexers.basic', 'MonkeyLexer'),
                     '.moo': ('pygments.lexers.scripting', 'MOOCodeLexer'),
                     '.moon': ('pygments.lexers.scripting', 'MoonScriptLexer'),
                     '.mos': ('pygments.lexers.mosel', 'MoselLexer'),
                     '.mount': ('pygments.lexers.configs', 'SystemdLexer'),
                     '.mpl': ('pygments.lexers.maple', 'MapleLexer'),
                     '.mq4': ('pygments.lexers.c_like', 'MqlLexer'),
                     '.mq5': ('pygments.lexers.c_like', 'MqlLexer'),
                     '.mqh': ('pygments.lexers.c_like', 'MqlLexer'),
                     '.ms': ('pygments.lexers.scripting', 'MiniScriptLexer'),
                     '.msc': ('pygments.lexers.dsls', 'MscgenLexer'),
                     '.mt': ('pygments.lexers.monte', 'MonteLexer'),
                     '.mu': ('pygments.lexers.algebra', 'MuPADLexer'),
                     '.mxml': ('pygments.lexers.actionscript', 'MxmlLexer'),
                     '.myt': ('pygments.lexers.templates', 'MyghtyLexer'),
                     '.n': ('pygments.lexers.dotnet', 'NemerleLexer'),
                     '.nasm': ('pygments.lexers.asm', 'NasmLexer'),
                     '.nb': ('pygments.lexers.algebra', 'MathematicaLexer'),
                     '.nbp': ('pygments.lexers.algebra', 'MathematicaLexer'),
                     '.nc': ('pygments.lexers.c_like', 'NesCLexer'),
                     '.ncl': ('pygments.lexers.ncl', 'NCLLexer'),
                     '.ndjson': ('pygments.lexers.data', 'JsonLexer'),
                     '.ng2': ('pygments.lexers.templates', 'Angular2HtmlLexer'),
                     '.ni': ('pygments.lexers.int_fiction', 'Inform7Lexer'),
                     '.nim': ('pygments.lexers.nimrod', 'NimrodLexer'),
                     '.nimrod': ('pygments.lexers.nimrod', 'NimrodLexer'),
                     '.nit': ('pygments.lexers.nit', 'NitLexer'),
                     '.nix': ('pygments.lexers.nix', 'NixLexer'),
                     '.nl': ('pygments.lexers.lisp', 'NewLispLexer'),
                     '.nqp': ('pygments.lexers.perl', 'Perl6Lexer'),
                     '.ns2': ('pygments.lexers.smalltalk', 'NewspeakLexer'),
                     '.nsh': ('pygments.lexers.installers', 'NSISLexer'),
                     '.nsi': ('pygments.lexers.installers', 'NSISLexer'),
                     '.nt': ('pygments.lexers.configs', 'NestedTextLexer'),
                     '.numba_ir': ('pygments.lexers.numbair', 'NumbaIRLexer'),
                     '.objdump': ('pygments.lexers.asm', 'ObjdumpLexer'),
                     '.objdump-intel': ('pygments.lexers.asm',
                                        'NasmObjdumpLexer'),
                     '.odin': ('pygments.lexers.archetype', 'OdinLexer'),
                     '.ooc': ('pygments.lexers.ooc', 'OocLexer'),
                     '.opa': ('pygments.lexers.ml', 'OpaLexer'),
                     '.orc': ('pygments.lexers.csound', 'CsoundOrchestraLexer'),
                     '.org': ('pygments.lexers.markup', 'OrgLexer'),
                     '.p': ('pygments.lexers.pawn', 'PawnLexer'),
                     '.p6': ('pygments.lexers.perl', 'Perl6Lexer'),
                     '.p6l': ('pygments.lexers.perl', 'Perl6Lexer'),
                     '.p6m': ('pygments.lexers.perl', 'Perl6Lexer'),
                     '.pack': ('pygments.lexers.vip', 'VisualPrologLexer'),
                     '.pan': ('pygments.lexers.dsls', 'PanLexer'),
                     '.pas': ('pygments.lexers.pascal', 'DelphiLexer'),
                     '.patch': ('pygments.lexers.diff', 'DiffLexer'),
                     '.path': ('pygments.lexers.configs', 'SystemdLexer'),
                     '.pc': ('pygments.lexers.configs', 'PkgConfigLexer'),
                     '.pcmk': ('pygments.lexers.dsls', 'CrmshLexer'),
                     '.pddl': ('pygments.lexers.pddl', 'PddlLexer'),
                     '.peg': ('pygments.lexers.grammar_notation', 'PegLexer'),
                     '.pem': ('pygments.lexers.asc', 'AscLexer'),
                     '.perl': ('pygments.lexers.perl', 'PerlLexer'),
                     '.ph': ('pygments.lexers.vip', 'VisualPrologLexer'),
                     '.php': ('pygments.lexers.php', 'PhpLexer'),
                     '.php[345]': ('pygments.lexers.php', 'PhpLexer'),
                     '.phtml': ('pygments.lexers.templates', 'HtmlPhpLexer'),
                     '.pidl': ('pygments.lexers.c_like', 'OmgIdlLexer'),
                     '.pig': ('pygments.lexers.jvm', 'PigLexer'),
                     '.pike': ('pygments.lexers.c_like', 'PikeLexer'),
                     '.pl': ('pygments.lexers.perl', 'Perl6Lexer'),
                     '.pl6': ('pygments.lexers.perl', 'Perl6Lexer'),
                     '.plot': ('pygments.lexers.graphics', 'GnuplotLexer'),
                     '.plt': ('pygments.lexers.graphics', 'GnuplotLexer'),
                     '.pm': ('pygments.lexers.perl', 'Perl6Lexer'),
                     '.pm6': ('pygments.lexers.perl', 'Perl6Lexer'),
                     '.pml': ('pygments.lexers.c_like', 'PromelaLexer'),
                     '.pmod': ('pygments.lexers.c_like', 'PikeLexer'),
                     '.po': ('pygments.lexers.textfmts', 'GettextLexer'),
                     '.pony': ('pygments.lexers.pony', 'PonyLexer'),
                     '.portugol': ('pygments.lexers.pascal', 'PortugolLexer'),
                     '.pot': ('pygments.lexers.textfmts', 'GettextLexer'),
                     '.pov': ('pygments.lexers.graphics', 'PovrayLexer'),
                     '.pp': ('pygments.lexers.dsls', 'PuppetLexer'),
                     '.pr': ('pygments.lexers.c_like', 'PromelaLexer'),
                     '.praat': ('pygments.lexers.praat', 'PraatLexer'),
                     '.prg': ('pygments.lexers.foxpro', 'FoxProLexer'),
                     '.prm': ('pygments.lexers.c_like', 'PromelaLexer'),
                     '.pro': ('pygments.lexers.prolog', 'PrologLexer'),
                     '.proc': ('pygments.lexers.praat', 'PraatLexer'),
                     '.prolog': ('pygments.lexers.prolog', 'PrologLexer'),
                     '.prom': ('pygments.lexers.c_like', 'PromelaLexer'),
                     '.promela': ('pygments.lexers.c_like', 'PromelaLexer'),
                     '.promql': ('pygments.lexers.promql', 'PromQLLexer'),
                     '.properties': ('pygments.lexers.configs',
                                     'PropertiesLexer'),
                     '.proto': ('pygments.lexers.dsls', 'ProtoBufLexer'),
                     '.prql': ('pygments.lexers.prql', 'PrqlLexer'),
                     '.ps': ('pygments.lexers.graphics', 'PostScriptLexer'),
                     '.ps1': ('pygments.lexers.shell', 'PowerShellLexer'),
                     '.psc': ('pygments.lexers.praat', 'PraatLexer'),
                     '.psi': ('pygments.lexers.parasail', 'ParaSailLexer'),
                     '.psl': ('pygments.lexers.parasail', 'ParaSailLexer'),
                     '.psm1': ('pygments.lexers.shell', 'PowerShellLexer'),
                     '.ptls': ('pygments.lexers.pointless', 'PointlessLexer'),
                     '.ptx': ('pygments.lexers.ptx', 'PtxLexer'),
                     '.pug': ('pygments.lexers.html', 'PugLexer'),
                     '.pwn': ('pygments.lexers.pawn', 'PawnLexer'),
                     '.pxd': ('pygments.lexers.python', 'CythonLexer'),
                     '.pxi': ('pygments.lexers.python', 'CythonLexer'),
                     '.py': ('pygments.lexers.python', 'Python3Lexer'),
                     '.py2tb': ('pygments.lexers.python',
                                'Python2TracebackLexer'),
                     '.py3tb': ('pygments.lexers.python',
                                'PythonTracebackLexer'),
                     '.pyi': ('pygments.lexers.python', 'PythonLexer'),
                     '.pypylog': ('pygments.lexers.console', 'PyPyLogLexer'),
                     '.pytb': ('pygments.lexers.python',
                               'Python3TracebackLexer'),
                     '.pyul4': ('pygments.lexers.ul4', 'PythonUL4Lexer'),
                     '.pyw': ('pygments.lexers.python', 'Python3Lexer'),
                     '.pyx': ('pygments.lexers.python', 'CythonLexer'),
                     '.q': ('pygments.lexers.q', 'QLexer'),
                     '.qbs': ('pygments.lexers.webmisc', 'QmlLexer'),
                     '.ql': ('pygments.lexers.codeql', 'CodeQLLexer'),
                     '.qll': ('pygments.lexers.codeql', 'CodeQLLexer'),
                     '.qml': ('pygments.lexers.webmisc', 'QmlLexer'),
                     '.qvs': ('pygments.lexers.qlik', 'QlikLexer'),
                     '.qvto': ('pygments.lexers.qvt', 'QVToLexer'),
                     '.qvw': ('pygments.lexers.qlik', 'QlikLexer'),
                     '.r': ('pygments.lexers.rebol', 'RebolLexer'),
                     '.r3': ('pygments.lexers.rebol', 'RebolLexer'),
                     '.rake': ('pygments.lexers.ruby', 'RubyLexer'),
                     '.raku': ('pygments.lexers.perl', 'Perl6Lexer'),
                     '.rakudoc': ('pygments.lexers.perl', 'Perl6Lexer'),
                     '.rakumod': ('pygments.lexers.perl', 'Perl6Lexer'),
                     '.rakutest': ('pygments.lexers.perl', 'Perl6Lexer'),
                     '.rb': ('pygments.lexers.ruby', 'RubyLexer'),
                     '.rbw': ('pygments.lexers.ruby', 'RubyLexer'),
                     '.rbx': ('pygments.lexers.ruby', 'RubyLexer'),
                     '.re': ('pygments.lexers.ml', 'ReasonLexer'),
                     '.react': ('pygments.lexers.jsx', 'JsxLexer'),
                     '.reb': ('pygments.lexers.rebol', 'RebolLexer'),
                     '.red': ('pygments.lexers.rebol', 'RedLexer'),
                     '.reds': ('pygments.lexers.rebol', 'RedLexer'),
                     '.reg': ('pygments.lexers.configs', 'RegeditLexer'),
                     '.rego': ('pygments.lexers.rego', 'RegoLexer'),
                     '.rei': ('pygments.lexers.ml', 'ReasonLexer'),
                     '.resource': ('pygments.lexers.robotframework',
                                   'RobotFrameworkLexer'),
                     '.rest': ('pygments.lexers.markup', 'RstLexer'),
                     '.rex': ('pygments.lexers.scripting', 'RexxLexer'),
                     '.rexx': ('pygments.lexers.scripting', 'RexxLexer'),
                     '.rhtml': ('pygments.lexers.templates', 'RhtmlLexer'),
                     '.ride': ('pygments.lexers.ride', 'RideLexer'),
                     '.rita': ('pygments.lexers.rita', 'RitaLexer'),
                     '.rkt': ('pygments.lexers.lisp', 'RacketLexer'),
                     '.rktd': ('pygments.lexers.lisp', 'RacketLexer'),
                     '.rktl': ('pygments.lexers.lisp', 'RacketLexer'),
                     '.rl': ('pygments.lexers.parsers', 'RagelCppLexer'),
                     '.rnc': ('pygments.lexers.rnc', 'RNCCompactLexer'),
                     '.robot': ('pygments.lexers.robotframework',
                                'RobotFrameworkLexer'),
                     '.rpf': ('pygments.lexers.dsls', 'VGLLexer'),
                     '.rq': ('pygments.lexers.rdf', 'SparqlLexer'),
                     '.rql': ('pygments.lexers.sql', 'RqlLexer'),
                     '.rs': ('pygments.lexers.rust', 'RustLexer'),
                     '.rs.in': ('pygments.lexers.rust', 'RustLexer'),
                     '.rsl': ('pygments.lexers.dsls', 'RslLexer'),
                     '.rss': ('pygments.lexers.html', 'XmlLexer'),
                     '.rst': ('pygments.lexers.markup', 'RstLexer'),
                     '.rts': ('pygments.lexers.trafficscript', 'RtsLexer'),
                     '.run': ('pygments.lexers.ampl', 'AmplLexer'),
                     '.rvt': ('pygments.lexers.tcl', 'TclLexer'),
                     '.rx': ('pygments.lexers.scripting', 'RexxLexer'),
                     '.s': ('pygments.lexers.asm', 'GasLexer'),
                     '.sage': ('pygments.lexers.python', 'Python3Lexer'),
                     '.sarl': ('pygments.lexers.jvm', 'SarlLexer'),
                     '.sas': ('pygments.lexers.sas', 'SASLexer'),
                     '.sass': ('pygments.lexers.css', 'SassLexer'),
                     '.savi': ('pygments.lexers.savi', 'SaviLexer'),
                     '.sbl': ('pygments.lexers.dsls', 'SnowballLexer'),
                     '.sc': ('pygments.lexers.python', 'Python3Lexer'),
                     '.scad': ('pygments.lexers.openscad', 'OpenScadLexer'),
                     '.scala': ('pygments.lexers.jvm', 'ScalaLexer'),
                     '.scaml': ('pygments.lexers.html', 'ScamlLexer'),
                     '.scd': ('pygments.lexers.supercollider',
                              'SuperColliderLexer'),
                     '.scdoc': ('pygments.lexers.scdoc', 'ScdocLexer'),
                     '.sce': ('pygments.lexers.matlab', 'ScilabLexer'),
                     '.sci': ('pygments.lexers.matlab', 'ScilabLexer'),
                     '.scm': ('pygments.lexers.lisp', 'SchemeLexer'),
                     '.sco': ('pygments.lexers.csound', 'CsoundScoreLexer'),
                     '.scope': ('pygments.lexers.configs', 'SystemdLexer'),
                     '.scss': ('pygments.lexers.css', 'ScssLexer'),
                     '.sed': ('pygments.lexers.textedit', 'SedLexer'),
                     '.service': ('pygments.lexers.configs', 'SystemdLexer'),
                     '.sgf': ('pygments.lexers.sgf', 'SmartGameFormatLexer'),
                     '.sh': ('pygments.lexers.shell', 'BashLexer'),
                     '.sh-session': ('pygments.lexers.shell',
                                     'BashSessionLexer'),
                     '.shell-session': ('pygments.lexers.shell',
                                        'BashSessionLexer'),
                     '.shen': ('pygments.lexers.lisp', 'ShenLexer'),
                     '.shex': ('pygments.lexers.rdf', 'ShExCLexer'),
                     '.sieve': ('pygments.lexers.sieve', 'SieveLexer'),
                     '.sig': ('pygments.lexers.ml', 'SMLLexer'),
                     '.sil': ('pygments.lexers.verification', 'SilverLexer'),
                     '.siv': ('pygments.lexers.sieve', 'SieveLexer'),
                     '.sl': ('pygments.lexers.shell', 'SlurmBashLexer'),
                     '.sla': ('pygments.lexers.slash', 'SlashLexer'),
                     '.slice': ('pygments.lexers.configs', 'SystemdLexer'),
                     '.slim': ('pygments.lexers.webmisc', 'SlimLexer'),
                     '.sls': ('pygments.lexers.templates', 'YamlJinjaLexer'),
                     '.smali': ('pygments.lexers.dalvik', 'SmaliLexer'),
                     '.smithy': ('pygments.lexers.smithy', 'SmithyLexer'),
                     '.sml': ('pygments.lexers.ml', 'SMLLexer'),
                     '.smv': ('pygments.lexers.smv', 'NuSMVLexer'),
                     '.snbt': ('pygments.lexers.minecraft', 'SNBTLexer'),
                     '.snobol': ('pygments.lexers.snobol', 'SnobolLexer'),
                     '.socket': ('pygments.lexers.configs', 'SystemdLexer'),
                     '.sol': ('pygments.lexers.solidity', 'SolidityLexer'),
                     '.sources': ('pygments.lexers.installers',
                                  'DebianSourcesLexer'),
                     '.sp': ('pygments.lexers.pawn', 'SourcePawnLexer'),
                     '.sparql': ('pygments.lexers.rdf', 'SparqlLexer'),
                     '.spec': ('pygments.lexers.installers', 'RPMSpecLexer'),
                     '.spice': ('pygments.lexers.spice', 'SpiceLexer'),
                     '.spt': ('pygments.lexers.templates', 'CheetahLexer'),
                     '.sql': ('pygments.lexers.sql', 'SqlLexer'),
                     '.sql.j2': ('pygments.lexers.templates', 'SqlJinjaLexer'),
                     '.sql.jinja2': ('pygments.lexers.templates',
                                     'SqlJinjaLexer'),
                     '.sqlite3-console': ('pygments.lexers.sql',
                                          'SqliteConsoleLexer'),
                     '.ss': ('pygments.lexers.lisp', 'SchemeLexer'),
                     '.ssp': ('pygments.lexers.templates', 'SspLexer'),
                     '.st': ('pygments.lexers.smalltalk', 'SmalltalkLexer'),
                     '.stan': ('pygments.lexers.modeling', 'StanLexer'),
                     '.sv': ('pygments.lexers.hdl', 'SystemVerilogLexer'),
                     '.svh': ('pygments.lexers.hdl', 'SystemVerilogLexer'),
                     '.swap': ('pygments.lexers.configs', 'SystemdLexer'),
                     '.swg': ('pygments.lexers.c_like', 'SwigLexer'),
                     '.swift': ('pygments.lexers.objective', 'SwiftLexer'),
                     '.t': ('pygments.lexers.perl', 'Perl6Lexer'),
                     '.tac': ('pygments.lexers.python', 'Python3Lexer'),
                     '.tact': ('pygments.lexers.tact', 'TactLexer'),
                     '.tal': ('pygments.lexers.tal', 'TalLexer'),
                     '.tap': ('pygments.lexers.testing', 'TAPLexer'),
                     '.target': ('pygments.lexers.configs', 'SystemdLexer'),
                     '.tasm': ('pygments.lexers.asm', 'TasmLexer'),
                     '.tcl': ('pygments.lexers.tcl', 'TclLexer'),
                     '.tcsh': ('pygments.lexers.shell', 'TcshLexer'),
                     '.td': ('pygments.lexers.tablegen', 'TableGenLexer'),
                     '.tea': ('pygments.lexers.templates', 'TeaTemplateLexer'),
                     '.teal': ('pygments.lexers.teal', 'TealLexer'),
                     '.tex': ('pygments.lexers.markup', 'TexLexer'),
                     '.tf': ('pygments.lexers.configs', 'TerraformLexer'),
                     '.thrift': ('pygments.lexers.dsls', 'ThriftLexer'),
                     '.thy': ('pygments.lexers.theorem', 'IsabelleLexer'),
                     '.ti': ('pygments.lexers.thingsdb', 'ThingsDBLexer'),
                     '.tid': ('pygments.lexers.markup', 'TiddlyWiki5Lexer'),
                     '.timer': ('pygments.lexers.configs', 'SystemdLexer'),
                     '.tlb': ('pygments.lexers.tlb', 'TlbLexer'),
                     '.tmpl': ('pygments.lexers.templates', 'CheetahLexer'),
                     '.tnt': ('pygments.lexers.tnt', 'TNTLexer'),
                     '.toc': ('pygments.lexers.wowtoc', 'WoWTocLexer'),
                     '.todotxt': ('pygments.lexers.textfmts', 'TodotxtLexer'),
                     '.toml': ('pygments.lexers.configs', 'TOMLLexer'),
                     '.tpl': ('pygments.lexers.templates', 'SmartyLexer'),
                     '.tpp': ('pygments.lexers.c_cpp', 'CppLexer'),
                     '.treetop': ('pygments.lexers.parsers', 'TreetopLexer'),
                     '.ts': ('pygments.lexers.javascript', 'TypeScriptLexer'),
                     '.tst': ('pygments.lexers.matlab', 'ScilabLexer'),
                     '.tsx': ('pygments.lexers.jsx', 'TsxLexer'),
                     '.tt': ('pygments.lexers.parsers', 'TreetopLexer'),
                     '.ttl': ('pygments.lexers.rdf', 'TurtleLexer'),
                     '.twig': ('pygments.lexers.templates', 'TwigHtmlLexer'),
                     '.txt': ('pygments.lexers.special', 'TextLexer'),
                     '.typ': ('pygments.lexers.typst', 'TypstLexer'),
                     '.typoscript': ('pygments.lexers.typoscript',
                                     'TypoScriptLexer'),
                     '.u': ('pygments.lexers.urbi', 'UrbiscriptLexer'),
                     '.u1': ('pygments.lexers.unicon', 'UcodeLexer'),
                     '.u2': ('pygments.lexers.unicon', 'UcodeLexer'),
                     '.udo': ('pygments.lexers.csound', 'CsoundOrchestraLexer'),
                     '.ul4': ('pygments.lexers.ul4', 'UL4Lexer'),
                     '.usd': ('pygments.lexers.usd', 'UsdLexer'),
                     '.usda': ('pygments.lexers.usd', 'UsdLexer'),
                     '.v': ('pygments.lexers.theorem', 'CoqLexer'),
                     '.vala': ('pygments.lexers.c_like', 'ValaLexer'),
                     '.vapi': ('pygments.lexers.c_like', 'ValaLexer'),
                     '.vark': ('pygments.lexers.jvm', 'GosuLexer'),
                     '.vb': ('pygments.lexers.dotnet', 'VbNetLexer'),
                     '.vbs': ('pygments.lexers.basic', 'VBScriptLexer'),
                     '.vcl': ('pygments.lexers.varnish', 'VCLLexer'),
                     '.vert': ('pygments.lexers.graphics', 'GLShaderLexer'),
                     '.vhd': ('pygments.lexers.hdl', 'VhdlLexer'),
                     '.vhdl': ('pygments.lexers.hdl', 'VhdlLexer'),
                     '.vim': ('pygments.lexers.textedit', 'VimLexer'),
                     '.vimrc': ('pygments.lexers.textedit', 'VimLexer'),
                     '.vipgrm': ('pygments.lexers.vip',
                                 'VisualPrologGrammarLexer'),
                     '.vm': ('pygments.lexers.templates', 'VelocityLexer'),
                     '.vp': ('pygments.lexers.verifpal', 'VerifpalLexer'),
                     '.vpr': ('pygments.lexers.verification', 'SilverLexer'),
                     '.vue': ('pygments.lexers.html', 'VueLexer'),
                     '.vy': ('pygments.lexers.vyper', 'VyperLexer'),
                     '.wast': ('pygments.lexers.webassembly', 'WatLexer'),
                     '.wat': ('pygments.lexers.webassembly', 'WatLexer'),
                     '.wdiff': ('pygments.lexers.diff', 'WDiffLexer'),
                     '.webidl': ('pygments.lexers.webidl', 'WebIDLLexer'),
                     '.weechatlog': ('pygments.lexers.textfmts',
                                     'IrcLogsLexer'),
                     '.wgsl': ('pygments.lexers.wgsl', 'WgslLexer'),
                     '.whiley': ('pygments.lexers.whiley', 'WhileyLexer'),
                     '.wlua': ('pygments.lexers.scripting', 'LuaLexer'),
                     '.wren': ('pygments.lexers.wren', 'WrenLexer'),
                     '.wsdl': ('pygments.lexers.html', 'XmlLexer'),
                     '.wsf': ('pygments.lexers.html', 'XmlLexer'),
                     '.x': ('pygments.lexers.objective', 'LogosLexer'),
                     '.x10': ('pygments.lexers.x10', 'X10Lexer'),
                     '.x[bp]m': ('pygments.lexers.c_cpp', 'CLexer'),
                     '.xhtml': ('pygments.lexers.html', 'HtmlLexer'),
                     '.xhtml.j2': ('pygments.lexers.templates',
                                   'HtmlDjangoLexer'),
                     '.xhtml.jinja2': ('pygments.lexers.templates',
                                       'HtmlDjangoLexer'),
                     '.xi': ('pygments.lexers.objective', 'LogosLexer'),
                     '.xm': ('pygments.lexers.objective', 'LogosLexer'),
                     '.xmi': ('pygments.lexers.objective', 'LogosLexer'),
                     '.xml': ('pygments.lexers.html', 'XmlLexer'),
                     '.xml.j2': ('pygments.lexers.templates', 'XmlDjangoLexer'),
                     '.xml.jinja2': ('pygments.lexers.templates',
                                     'XmlDjangoLexer'),
                     '.xmlul4': ('pygments.lexers.ul4', 'XMLUL4Lexer'),
                     '.xpl': ('pygments.lexers.html', 'XsltLexer'),
                     '.xpp': ('pygments.lexers.dotnet', 'XppLexer'),
                     '.xq': ('pygments.lexers.webmisc', 'XQueryLexer'),
                     '.xql': ('pygments.lexers.webmisc', 'XQueryLexer'),
                     '.xqm': ('pygments.lexers.webmisc', 'XQueryLexer'),
                     '.xquery': ('pygments.lexers.webmisc', 'XQueryLexer'),
                     '.xqy': ('pygments.lexers.webmisc', 'XQueryLexer'),
                     '.xsd': ('pygments.lexers.html', 'XmlLexer'),
                     '.xsh': ('xonsh.pyghooks', 'XonshLexer'),
                     '.xsl': ('pygments.lexers.html', 'XsltLexer'),
                     '.xslt': ('pygments.lexers.html', 'XsltLexer'),
                     '.xtend': ('pygments.lexers.jvm', 'XtendLexer'),
                     '.xtm': ('pygments.lexers.lisp', 'XtlangLexer'),
                     '.xul.in': ('pygments.lexers.markup',
                                 'MozPreprocXulLexer'),
                     '.yaml': ('pygments.lexers.data', 'YamlLexer'),
                     '.yaml.j2': ('pygments.lexers.templates',
                                  'YamlJinjaLexer'),
                     '.yaml.jinja2': ('pygments.lexers.templates',
                                      'YamlJinjaLexer'),
                     '.yang': ('pygments.lexers.yang', 'YangLexer'),
                     '.yar': ('pygments.lexers.yara', 'YaraLexer'),
                     '.yml': ('pygments.lexers.data', 'YamlLexer'),
                     '.yml.j2': ('pygments.lexers.templates', 'YamlJinjaLexer'),
                     '.yml.jinja2': ('pygments.lexers.templates',
                                     'YamlJinjaLexer'),
                     '.zeek': ('pygments.lexers.dsls', 'ZeekLexer'),
                     '.zep': ('pygments.lexers.php', 'ZephirLexer'),
                     '.zig': ('pygments.lexers.zig', 'ZigLexer'),
                     '.zone': ('pygments.lexers.dns', 'DnsZoneLexer'),
                     '.zsh': ('pygments.lexers.shell', 'BashLexer'),
                     '.zshrc': ('pygments.lexers.shell', 'BashLexer'),
                     '.🔥': ('pygments.lexers.mojo', 'MojoLexer'),
                     'Android.bp': ('pygments.lexers.soong', 'SoongLexer'),
                     'BUCK': ('pygments.lexers.python', 'PythonLexer'),
                     'BUILD': ('pygments.lexers.python', 'PythonLexer'),
                     'BUILD.bazel': ('pygments.lexers.python', 'PythonLexer'),
                     'CMakeLists.txt': ('pygments.lexers.make', 'CMakeLexer'),
                     'Dockerfile': ('pygments.lexers.configs', 'DockerLexer'),
                     'GNUmakefile': ('pygments.lexers.make', 'MakefileLexer'),
                     'Gemfile': ('pygments.lexers.ruby', 'RubyLexer'),
                     'Makefile': ('pygments.lexers.make', 'MakefileLexer'),
                     'PKGBUILD': ('pygments.lexers.shell', 'BashLexer'),
                     'Pipfile': ('pygments.lexers.configs', 'TOMLLexer'),
                     'Pipfile.lock': ('pygments.lexers.data', 'JsonLexer'),
                     'Procfile': ('pygments.lexers.procfile', 'ProcfileLexer'),
                     'Rakefile': ('pygments.lexers.ruby', 'RubyLexer'),
                     'SConscript': ('pygments.lexers.python', 'Python3Lexer'),
                     'SConstruct': ('pygments.lexers.python', 'Python3Lexer'),
                     'Singularity': ('pygments.lexers.configs',
                                     'SingularityLexer'),
                     'Vagrantfile': ('pygments.lexers.ruby', 'RubyLexer'),
                     'WORKSPACE': ('pygments.lexers.python', 'PythonLexer'),
                     '_exrc': ('pygments.lexers.textedit', 'VimLexer'),
                     '_gvimrc': ('pygments.lexers.textedit', 'VimLexer'),
                     '_vimrc': ('pygments.lexers.textedit', 'VimLexer'),
                     'apache.conf': ('pygments.lexers.configs',
                                     'ApacheConfLexer'),
                     'apache2.conf': ('pygments.lexers.configs',
                                      'ApacheConfLexer'),
                     'autodelegate': ('pygments.lexers.templates',
                                      'MyghtyLexer'),
                     'autohandler': ('pygments.lexers.templates', 'MasonLexer'),
                     'bashrc': ('pygments.lexers.shell', 'BashLexer'),
                     'control': ('pygments.lexers.installers',
                                 'DebianControlLexer'),
                     'dhandler': ('pygments.lexers.templates', 'MasonLexer'),
                     'gvimrc': ('pygments.lexers.textedit', 'VimLexer'),
                     'id_dsa': ('pygments.lexers.asc', 'AscLexer'),
                     'id_ecdsa': ('pygments.lexers.asc', 'AscLexer'),
                     'id_ecdsa_sk': ('pygments.lexers.asc', 'AscLexer'),
                     'id_ed25519': ('pygments.lexers.asc', 'AscLexer'),
                     'id_ed25519_sk': ('pygments.lexers.asc', 'AscLexer'),
                     'id_rsa': ('pygments.lexers.asc', 'AscLexer'),
                     'kshrc': ('pygments.lexers.shell', 'BashLexer'),
                     'ldap.conf': ('pygments.lexers.ldap', 'LdaprcLexer'),
                     'ldaprc': ('pygments.lexers.ldap', 'LdaprcLexer'),
                     'lighttpd.conf': ('pygments.lexers.configs',
                                       'LighttpdConfLexer'),
                     'makefile': ('pygments.lexers.make', 'MakefileLexer'),
                     'meson.build': ('pygments.lexers.meson', 'MesonLexer'),
                     'meson_options.txt': ('pygments.lexers.meson',
                                           'MesonLexer'),
                     'nginx.conf': ('pygments.lexers.configs',
                                    'NginxConfLexer'),
                     'pacman.conf': ('pygments.lexers.configs',
                                     'PacmanConfLexer'),
                     'poetry.lock': ('pygments.lexers.configs', 'TOMLLexer'),
                     'sources.list': ('pygments.lexers.installers',
                                      'SourcesListLexer'),
                     'squid.conf': ('pygments.lexers.configs',
                                    'SquidConfLexer'),
                     'standard-modules.in': ('pygments.lexers.configs',
                                             'KconfigLexer'),
                     'termcap': ('pygments.lexers.configs', 'TermcapLexer'),
                     'termcap.src': ('pygments.lexers.configs', 'TermcapLexer'),
                     'terminfo': ('pygments.lexers.configs', 'TerminfoLexer'),
                     'terminfo.src': ('pygments.lexers.configs',
                                      'TerminfoLexer'),
                     'todo.txt': ('pygments.lexers.textfmts', 'TodotxtLexer'),
                     'vimrc': ('pygments.lexers.textedit', 'VimLexer'),
                     'xorg.conf': ('pygments.lexers.xorg', 'XorgLexer'),
                     'zshrc': ('pygments.lexers.shell', 'BashLexer')}},
 'styles': {'names': {'abap': ('pygments.styles.abap', 'AbapStyle'),
                      'algol': ('pygments.styles.algol', 'AlgolStyle'),
                      'algol_nu': ('pygments.styles.algol_nu', 'Algol_NuStyle'),
                      'arduino': ('pygments.styles.arduino', 'ArduinoStyle'),
                      'autumn': ('pygments.styles.autumn', 'AutumnStyle'),
                      'borland': ('pygments.styles.borland', 'BorlandStyle'),
                      'bw': ('pygments.styles.bw', 'BlackWhiteStyle'),
                      'coffee': ('pygments.styles.coffee', 'CoffeeStyle'),
                      'colorful': ('pygments.styles.colorful', 'ColorfulStyle'),
                      'default': ('pygments.styles.default', 'DefaultStyle'),
                      'dracula': ('pygments.styles.dracula', 'DraculaStyle'),
                      'emacs': ('pygments.styles.emacs', 'EmacsStyle'),
                      'friendly': ('pygments.styles.friendly', 'FriendlyStyle'),
                      'friendly_grayscale': ('pygments.styles.friendly_grayscale',
                                             'FriendlyGrayscaleStyle'),
                      'fruity': ('pygments.styles.fruity', 'FruityStyle'),
                      'github-dark': ('pygments.styles.gh_dark', 'GhDarkStyle'),
                      'gruvbox-dark': ('pygments.styles.gruvbox',
                                       'GruvboxDarkStyle'),
                      'gruvbox-light': ('pygments.styles.gruvbox',
                                        'GruvboxLightStyle'),
                      'igor': ('pygments.styles.igor', 'IgorStyle'),
                      'inkpot': ('pygments.styles.inkpot', 'InkPotStyle'),
                      'lightbulb': ('pygments.styles.lightbulb',
                                    'LightbulbStyle'),
                      'lilypond': ('pygments.styles.lilypond', 'LilyPondStyle'),
                      'lovelace': ('pygments.styles.lovelace', 'LovelaceStyle'),
                      'manni': ('pygments.styles.manni', 'ManniStyle'),
                      'material': ('pygments.styles.material', 'MaterialStyle'),
                      'monokai': ('pygments.styles.monokai', 'MonokaiStyle'),
                      'murphy': ('pygments.styles.murphy', 'MurphyStyle'),
                      'native': ('pygments.styles.native', 'NativeStyle'),
                      'nord': ('pygments.styles.nord', 'NordStyle'),
                      'nord-darker': ('pygments.styles.nord',
                                      'NordDarkerStyle'),
                      'one-dark': ('pygments.styles.onedark', 'OneDarkStyle'),
                      'paraiso-dark': ('pygments.styles.paraiso_dark',
                                       'ParaisoDarkStyle'),
                      'paraiso-light': ('pygments.styles.paraiso_light',
                                        'ParaisoLightStyle'),
                      'pastie': ('pygments.styles.pastie', 'PastieStyle'),
                      'perldoc': ('pygments.styles.perldoc', 'PerldocStyle'),
                      'rainbow_dash': ('pygments.styles.rainbow_dash',
                                       'RainbowDashStyle'),
                      'rrt': ('pygments.styles.rrt', 'RrtStyle'),
                      'sas': ('pygments.styles.sas', 'SasStyle'),
                      'solarized-dark': ('pygments.styles.solarized',
                                         'SolarizedDarkStyle'),
                      'solarized-light': ('pygments.styles.solarized',
                                          'SolarizedLightStyle'),
                      'staroffice': ('pygments.styles.staroffice',
                                     'StarofficeStyle'),
                      'stata-dark': ('pygments.styles.stata_dark',
                                     'StataDarkStyle'),
                      'stata-light': ('pygments.styles.stata_light',
                                      'StataLightStyle'),
                      'tango': ('pygments.styles.tango', 'TangoStyle'),
                      'trac': ('pygments.styles.trac', 'TracStyle'),
                      'vim': ('pygments.styles.vim', 'VimStyle'),
                      'vs': ('pygments.styles.vs', 'VisualStudioStyle'),
                      'xcode': ('pygments.styles.xcode', 'XcodeStyle'),
                      'zenburn': ('pygments.styles.zenburn', 'ZenburnStyle')}}}