section: screens
	mahd-mbp:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
	mahd-server-1:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
end

section: aliases
end

section: links
	mahd-mbp:
		right = mahd-server-1
	mahd-server-1:
		left = mahd-mbp
end

section: options
	heartbeat = 5000
	protocol = barrier
	relativeMouseMoves = false
	win32KeepForeground = false
	disableLockToScreen = false
	clipboardSharing = true
	clipboardSharingSize = 3072
	switchCorners = none 
	switchCornerSize = 0
end

