;; -*- lexical-binding: t; tab-width: 8; -*-
;; Updated: 2025-09-09 13:07:33
;; Generated by 'doom profile sync' or 'doom sync'.
;; DO NOT EDIT THIS BY HAND!
"3.0.0-pre"
(pcase (intern (getenv-internal "DOOMPROFILE")) ('safe-mode (let nil (setq user-emacs-directory (expand-file-name "safe-mode/" (expand-file-name "~/DEV/dotfiles-macos/.config/emacs/profiles" user-emacs-directory))))))(setq user-emacs-directory (file-name-as-directory user-emacs-directory))