#define ABS_SRCDIR "/Users/mahd/.rvm/src/ruby-3.0.0"
#define BUILDDIR   "/Users/mahd/.rvm/src/ruby-3.0.0"
#define LIBPATHENV "DYLD_FALLBACK_LIBRARY_PATH"
#define PRELOADENV "DYLD_INSERT_LIBRARIES"
#define PATH_SEPARATOR ":"
#define PATH_SEP   ':'
#define EXTOUT     ".ext"
#define ARCH       "arm64-darwin23"
#define SOEXT      "dylib"
