#!/bin/bash

# Set default layout
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Padding set to 6px
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 0

# Center mouse on window with focus
yabai -m config mouse_follows_focus on

# Modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# Set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# Set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# When window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

# Disable window management for certain applications
yabai -m rule --add app="^System Settings" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off

# Set external bar height and position
yabai -m config external_bar all:35:0
# Start Yabai borders
borders active_color=0x00ff0077 inactive_color=0xff000077 width=5.0 &
