#!/bin/bash

# Set default layout
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Padding set to 6px
yabai -m config top_padding 1
yabai -m config bottom_padding 1
yabai -m config left_padding 1
yabai -m config right_padding 1
yabai -m config window_gap 1

# Center mouse on window with focus
yabai -m config mouse_follows_focus on

# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autofocus

# Modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# Set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# Set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# When window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

# Disable window management for certain applications
yabai -m rule --add app="^System Settings" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^java$" manage=off
yabai -m rule --add app="^Minecraft$" manage=off
yabai -m rule --add app="^Loopback$" manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on manage=off

# Set external bar height and position
yabai -m config external_bar all:0:0

# on or off (default: off)
yabai -m config auto_balance on
# Floating point value between 0 and 1 (default: 0.5)
yabai -m config split_ratio 0.5