console_title_template = '{{.PWD}}{{if .Root}} : root{{end}} : {{.Shell}}'
version = 3
final_space = true

[transient_prompt]
  template = '󰁔 '
  foreground = 'white'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '╭─'
    foreground = 'white'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '
    foreground = 'black'
    background = 'white'
    type = 'os'
    style = 'plain'

    [blocks.segments.properties]
      alma = ''
      android = ''
      arch = '󰣇'
      cache_duration = 'none'
      debian = ''
      fedora = ''
      linux = ''
      macos = ''
      manjaro = '󱘊'
      redhat = ''
      rocky = ''
      ubuntu = ''
      windows = ''

  [[blocks.segments]]
    template = ''
    foreground = 'white'
    background = 'blue'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '  {{.Path}} '
    foreground = 'white'
    background = 'blue'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = ''
    foreground = 'blue'
    background = 'black'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ if .SSHSession }}󰣀 {{ end }}{{ .UserName }}@{{ .HostName }} '
    foreground = 'white'
    background = 'black'
    type = 'session'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ''
    foreground = 'black'
    background = 'white'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    foreground = 'black'
    background = 'white'
    type = 'shell'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

      [blocks.segments.properties.mapped_shell_names]
        bash = ''
        powershell = ''
        pwsh = ''
        zsh = 'zsh'

  [[blocks.segments]]
    template = ''
    foreground = 'white'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = ''
    foreground = 'white'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' at {{.CurrentDate | date .Format}}  '
    foreground = 'black'
    background = 'white'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      time_format = '02/01/2006 | 15:04:05.000'

  [[blocks.segments]]
    template = '─╮'
    foreground = 'white'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰─'
    foreground = 'white'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '$'
    foreground = 'white'
    background = 'transparent'
    type = 'root'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' '
    foreground = 'white'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'rprompt'
  alignment = 'right'

  [[blocks.segments]]
    template = '─╯'
    foreground = 'white'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
